#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#928374"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

bspc node @^1:/ -i
bspc node @^1:/ -p east -i
bspc node @^1:/1 -p east -i
bspc node @^1:/2 -p east -i
bspc node @^1:/2/2 -p south -i

bspc rule --add Slack:slack -o node=@^1:/1/1
bspc rule --add Brave-browser:brave-browser -o node=@^1:/1/2
bspc rule --add st-256color:neomutt -o node=@^1:/2/1
bspc rule --add KeePassXC:keepassxc -o node=@^1:/2/2/1
bspc rule --add "Yubico Authenticator":yubioath-desktop -o node=@^1:/2/2/2
