fpath=( $ZDOTDIR/zfunc "${fpath[@]}" )

logfile=/tmp/zshrc.log

for file in $(ls -1 "$ZDOTDIR"/zsh.d/); do
    echo "Sourcing $ZDOTDIR/zsh.d/$file" >> "$logfile"
    source "$ZDOTDIR/zsh.d/$file" >> "$logfile" 2>&1
done

if (( ${+ZSHRC_HOOK} )); then
    echo "Sourcing $ZSHRC_HOOK" >> "$logfile"
    source "$ZSHRC_HOOK" >> "$logfile" 2>&1
fi
