if [ ! -d "$XDG_DATA_HOME"/zsh ]; then
    mkdir -p "$XDG_DATA_HOME"/zsh
fi

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=10000000
SAVEHIST=10000000
setopt hist_ignore_all_dups

bindkey -v

zstyle :compinstall filename '/home/chris/.zshrc'

zstyle ":completion:*:(ssh|rsync|scp):*" hosts $hosts

fpath=( ~/.zfunc "${fpath[@]}" )

zstyle ':completion:*' menu select
autoload -Uz compinit
compinit

# Use shift+tab for going backward in completion menu
zmodload -i zsh/complist
bindkey -M menuselect '^[[Z' reverse-menu-complete

source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/prompt.zsh
source $ZDOTDIR/vim-mode.zsh
source $ZDOTDIR/fzf.zsh
source $ZDOTDIR/tmux.zsh
source $ZDOTDIR/augment_path.zsh

# Run startx on login
if [[ -z "${DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
    exec startx "$XDG_CONFIG_HOME/X11/xinitrc"
fi

# SSH agent
if ! [ -z "${XDG_RUNTIME_DIR}" ]; then
    if ! pgrep -u "$USER" ssh-agent > /dev/null; then
        ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
    fi
    if (( ! ${+SSH_AUTH_SOCK} )); then
        source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
    fi
fi

autoload bashcompinit && bashcompinit
complete -C '/usr/bin/aws_completer' aws

