require("plugins")
require("settings")
require("colorscheme")
require("keymappings")

require("lsp")

require("nv-compe")
require("nv-treesitter")
require("nv-ts-rainbow")
require("nv-autopairs")
require("nv-galaxyline")
require("nv-gitsigns")
require("nv-colorizer")
require("nv-barbar")
require("nv-hop")
require("nv-autocommands")
