#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift &
pgrep -x xss-lock > /dev/null || xss-lock ~/scripts/lock.sh &

"$XDG_CONFIG_HOME"/polybar/launch.sh
"$XDG_CONFIG_HOME"/bspwm_unique/create_desktops.sh

BW=9
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#928374"
bspc config focused_border_color "#cc241d"
bspc config presel_feedback_color "#b8bb26"

bspc rule --add Peek:peek state=floating focus=on center=on

if [ "$1" -gt 0 ]; then
    is_restart=true
else
    is_restart=false
fi
if ! "$is_restart" && [ -e "$XDG_CONFIG_HOME"/bspwm_unique/create_startup_layout.sh ] ; then
    "$XDG_CONFIG_HOME"/bspwm_unique/create_startup_layout.sh
fi
