#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

BW=3
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#928374"
bspc config focused_border_color "#b8bb26"
bspc config presel_feedback_color "#b8bb26"

bspc node @^1:/ --insert-receptacle
bspc node @^1:/ --presel-dir east --insert-receptacle

bspc rule --add Slack:slack --one-shot node=@^1:/1
bspc rule --add KeePassXC:keepassxc --one-shot node=@^1:/2

slack &
keepassxc &
