#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift &
pgrep -x xss-lock > /dev/null || xss-lock ~/scripts/lock.sh &
pgrep -xf "/bin/sh ${SCRIPTDIR}/notify_desktop_change.sh" > /dev/null || /bin/sh ~/scripts/notify_desktop_change.sh &

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

if [ "$(cat /etc/hostname)" = 'archie-work' ]; then
    bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
fi

BW=3
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#928374"
bspc config focused_border_color "#b8bb26"
bspc config presel_feedback_color "#b8bb26"

if [ "$1" -gt 0 ]; then
    is_restart=true
else
    is_restart=false
fi

if [ "$(cat /etc/hostname)" = 'archie-work' ] && ! "$is_restart" ; then
    bspc node @^1:/ --insert-receptacle
    bspc node @^1:/ --presel-dir east --insert-receptacle
    bspc node @^DESKTOP:/ --insert-receptacle

    bspc rule --add Slack:slack --one-shot node=@^1:/1
    bspc rule --add KeePassXC:keepassxc --one-shot node=@^1:/2
    bspc rule --add st-256color:st-256color --one-shot node=@^DESKTOP:/

    slack &
    keepassxc &
    st &
fi
