name: docker

on:
  push:
    branches:
      - 'main'
    paths:
      - '**/docker/**'
      - '**/dotfiles/gh/**'
      - '**/dotfiles/git/**'
      - '**/dotfiles/nvim/**'
      - '**/dotfiles/starship/**'
      - '**/dotfiles/zsh/**'
      - '**/dotfiles/zshenv/**'

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: [3.8]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cblessing24/python${{ matrix.python_version }}
          flavor: |
            latest=true
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: 'docker/Dockerfile'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
